# Generated by Django 4.0.5 on 2022-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=200)),
                ('vegetarienne', models.BooleanField(default=False)),
                ('prix', models.FloatField(default=0)),
            ],
        ),
    ]
